version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
       - ./backend/data:/app/data
    networks:
      - app_net
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app_net
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.local

networks:
  app_net:
    driver: bridge